SELECT DATE_FORMAT(SALES_DATE, '%Y') YEAR, 
    DATE_FORMAT(SALES_DATE, '%m') MONTH,
    COUNT(DISTINCT UI.USER_ID) PUCHASED_USERS,
    ROUND(COUNT(DISTINCT UI.USER_ID) / (SELECT COUNT(USER_ID) FROM USER_INFO WHERE DATE_FORMAT(JOINED, '%Y') = '2021'), 1) PUCHASED_RATIO
FROM USER_INFO UI
JOIN ONLINE_SALE OS
ON UI.USER_ID = OS.USER_ID
WHERE DATE_FORMAT(JOINED, '%Y') = '2021'
GROUP BY YEAR, MONTH