WITH VT AS (
    SELECT DAILY_FEE, HISTORY_ID, CAR_TYPE, DATEDIFF(END_DATE, START_DATE)+1 DURATION,
    CASE
        WHEN DATEDIFF(END_DATE, START_DATE)+1 >= 90 THEN '90일 이상'
        WHEN DATEDIFF(END_DATE, START_DATE)+1 >= 30 THEN '30일 이상'
        WHEN DATEDIFF(END_DATE, START_DATE)+1 >= 7 THEN '7일 이상'
        ELSE 'None'
    END DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY RH
    JOIN CAR_RENTAL_COMPANY_CAR CC
    ON RH.CAR_ID = CC.CAR_ID
    WHERE CAR_TYPE = '트럭'
)

SELECT HISTORY_ID, ROUND(DAILY_FEE * DURATION * (100-IFNULL(DISCOUNT_RATE, 0))/100) FEE
FROM VT
LEFT OUTER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN DP
ON VT.CAR_TYPE = DP.CAR_TYPE AND VT.DURATION_TYPE = DP.DURATION_TYPE
ORDER BY FEE DESC, HISTORY_ID DESC;