SELECT CC.CAR_ID, CC.CAR_TYPE, ROUND(DAILY_FEE*30*(100-DISCOUNT_RATE)/100, 0) FEE
FROM CAR_RENTAL_COMPANY_CAR CC
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN DP
    ON CC.CAR_TYPE = DP.CAR_TYPE
WHERE (CC.CAR_TYPE = '세단' OR CC.CAR_TYPE = 'SUV')
    AND CC.CAR_ID NOT IN (
        SELECT CAR_ID 
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY RH
        WHERE '2022-11-01' <= END_DATE AND START_DATE <= '2022-11-30'
        )
    AND DP.DURATION_TYPE = '30일 이상'
GROUP BY CC.CAR_ID
HAVING FEE BETWEEN 500000 AND 1999999
ORDER BY FEE DESC, CC.CAR_TYPE ASC, CC.CAR_ID DESC;