SELECT FR.PRODUCT_ID, PRODUCT_NAME, SUM(AMOUNT)*PRICE AS TOTAL_SALES
FROM FOOD_PRODUCT as FR, FOOD_ORDER as FO
WHERE FR.PRODUCT_ID = FO.PRODUCT_ID AND DATE_FORMAT(PRODUCE_DATE, '%Y%m') = '202205'
GROUP BY FR.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, FR.PRODUCT_ID ASC;